# -*- coding: utf-8 -*-
"""tarefa_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gqrxrpNtl08wMMxMy5lEuvBV4dn42D3G

Atividade 1
"""

print("Python é demais!")

"""Atividade 2"""

nome_completo = "Greice Braga Pereira"
idade = 18

print("Me chamo " + nome_completo + " e tenho " + str(idade) + " anos.")

"""Atividade 3"""

valor1 = int(input("Digite o primeiro valor: "))
valor2 = int(input("Digite o segundo valor: "))

soma = valor1 + valor2
subtracao = valor1 - valor2
multiplicacao = valor1 * valor2
divisao = valor1 / valor2

print("O resultado de " + str(valor1) + " + " + str(valor2) + " = " + str(soma) +
      ", de " + str(valor1) + " - " + str(valor2) + " = " + str(subtracao) +
      ", de " + str(valor1) + " * " + str(valor2) + " = " + str(multiplicacao) +
      " e de " + str(valor1) + " / " + str(valor2) + " = " + str(divisao))

"""Atividade 4"""

nome = input("Digite o nome: ")
sobrenome = input("Digite o sobrenome: ")

nome_completo = nome + " " + sobrenome

print("Nome completo: " + nome_completo)

"""Atividade 5"""

caractere = input("Digite um caractere: ")
print("O caractere digitado foi " + caractere)

"""Atividade 6"""

ano_atual = int(input("Digite o ano atual: "))
idade = int(input("Digite sua idade: "))

ano_nascimento_ja_fez_aniversario = ano_atual - idade
ano_nascimento_nao_fez_aniversario = ano_atual - idade - 1

print("Seu ano de nascimento, considerando que você já fez aniversário este ano, é: " + str(ano_nascimento_ja_fez_aniversario))
print("Seu ano de nascimento, considerando que você ainda não fez aniversário este ano, é: " + str(ano_nascimento_nao_fez_aniversario))

"""Atividade 7

"""

num_1 = int(input("Digite o primeiro número: "))
print("O antecessor de " + str(num_1) + " é " + str(num_1 - 1) + " e o sucessor é " + str(num_1 + 1))