# -*- coding: utf-8 -*-
"""tarefa_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aW67EjQHkOEIokDzoOm7SrKow6jPy6U2

Atividade 1
"""

# Entradas
nome = input("Digite o nome do vendedor: ")
salario_fixo = float(input("Digite o salário fixo: "))
total_vendas = float(input("Digite o total de vendas efetuadas no mês: "))

# Cálculos
comissao = total_vendas * 0.15
remuneracao_final = salario_fixo + comissao

# Resultado
print("A remuneração final de " + str(nome) + " é de R$ " + str(remuneracao_final))

"""Atividade 2"""

# Entradas
tempo = float(input("Digite o tempo gasto na viagem (em horas): "))
velocidade = float(input("Digite a velocidade média durante a viagem (em km/h): "))

# Cálculos
distancia = tempo * velocidade
litros = distancia / 12

# Resultado
print("A quantidade de gasolina necessária é de " + str(litros) + " litros.")

"""Atividade 3"""

# Valores
valores = [
    "abc",  # Valor 0
    range(0),  # Valor 1
    123456.789,  # Valor 2
    -5,  # Valor 3
    None,  # Valor 4
    not(False),  # Valor 5
    False,  # Valor 6
    print()  # Valor 7
]

# Resultados
print("Valor a:", bool(valores[0]))
print("Valor b:", bool(valores[1]))
print("Valor c:", bool(valores[2]))
print("Valor d:", bool(valores[3]))
print("Valor e:", bool(valores[4]))
print("Valor f:", bool(valores[5]))
print("Valor g:", bool(valores[6]))
print("Valor h:", bool(valores[7]))

"""Atividade 4"""

# Preços
preco_camiseta = 20.00
preco_calca = 50.00
preco_sapato = 100.00

# Entradas
num_camisetas = int(input("Digite o número de camisetas vendidas: "))
num_calcas = int(input("Digite o número de calças vendidas: "))
num_sapatos = int(input("Digite o número de sapatos vendidos: "))

# Armazenamento
vendas = [num_camisetas, num_calcas, num_sapatos]

# Cálculos
total_camisetas = vendas[0] * preco_camiseta
total_calcas = vendas[1] * preco_calca
total_sapatos = vendas[2] * preco_sapato

# Cálculos do Total Geral
total_geral = total_camisetas + total_calcas + total_sapatos

# Resultados
print("Total de vendas de camisetas: R$" + str(total_camisetas))
print("Total de vendas de calças: R$" + str(total_calcas))
print("Total de vendas de sapatos: R$" + str(total_sapatos))
print("Total geral de vendas: R$" + str(total_geral))